<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Аватарка' => '',
  'Выйти' => '',
  'Изменить пароль' => '',
  'Личный кабинет' => '',
  'Найти' => '',
  'Некорректное фото' => '',
  'Новый пароль' => '',
  'Отправить' => '',
  'Ошибка' => '',
  'Ошибка загрузки фото' => '',
  'Первая' => '',
  'Подтвердите пароль' => '',
  'Поиск' => '',
  'Получить ID' => '',
  'Последняя' => '',
  'Предыдущая' => '',
  'Произошла внутренняя ошибка сервера при создании маршрута. Пожалуйста попробуйте ещё раз.3' => '',
  'Произошла внутренняя ошибка сервера. Пожалуйста попробуйте ещё раз.' => '',
  'Произошла внутренняя ошибка сервера. Пожалуйста попробуйте ещё раз.1' => '',
  'Произошла внутренняя ошибка сервера. Пожалуйста попробуйте ещё раз.2' => '',
  'Произошла внутренняя ошибка сервера. Пожалуйста попробуйте ещё раз.4' => '',
  'Сбросить' => '',
  'Следующая' => '',
  'Создать' => '',
  'Сохранить' => '',
  'Старый пароль' => '',
  'Фильтровать' => '',
  'Фото' => '',
);
