<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '\\nВаш ID в сервисе Непотеряка: ' => '',
  'Активация объявления' => '',
  'Бюро находок' => '',
  'Ваш ID в сервисе Непотеряйка' => '',
  'Ваш код для возрата утерянного объекта в сервисе ' => '',
  'Ваш пароль на сайте ' => '',
  'Ваш пароль на сайте INFOtoway : ' => '',
  'Ваш пароль успешно изменен и отправлен через SMS!' => '',
  'Войти' => '',
  'Данный номер телефона не зарегестрирован' => '',
  'Для активации поданного объявления укажите код, отправленный по SMS на номер +{{phone}}<br /><a id="change-phone" href="#" class="ajax">Отправить на другой номер?</a>' => '',
  'Единая информационная служба' => '',
  'Забыли пароль?' => '',
  'Код активации' => '',
  'Код подверждения смены логина на сайте INFOtoway.ru : ' => '',
  'Личный кабинет' => '',
  'Мои объявления' => '',
  'Мой профиль' => '',
  'Написать автору' => '',
  'Не пришёл код активации?' => '',
  'Неверный телефон<br /> или пароль' => '',
  'Непотеряйка' => '',
  'Номер телефона' => '',
  'Ночлег' => '',
  'Пароль' => '',
  'Попутчик' => '',
  'Предыдущая' => '',
  0 => '',
  'Прислать новый пароль' => '',
  'Следующая' => '',
  'Телефон' => '',
  'Укажите номер сотового телефона' => '',
  'Указан неверный код активации.' => '',
);
