<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Ваш серивис не помог!' => '',
  'Да' => '',
  'Единая информационная служба' => '',
  'Извините, ошибка! Попробуйте еще раз позже.' => '',
  'Мне помог ваш сервис!' => '',
  'Нет' => '',
  'Нет спасибо' => '',
  'Отправить' => '',
  'Отчасти' => '',
  'Отчасти помог...' => '',
  'Поделитесь с нами вашим пожеланием' => '',
  'Помог ли Вам наш сервис?' => '',
  'Расскажите нам по секрету…' => '',
  'Спасибо! Благодаря Вам сервис станет лучше.' => '',
  'Телефон горячей линии' => '',
);
