<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Выберите населённый пункт из списка' => '',
  'Город' => '',
  'Заполните адрес' => '',
  'Ничего не найдено' => '',
  'Откуда' => '',
  'Пожалуйста исправьте указанные ошибки' => '',
  'Укажите ID найденного объекта' => '',
  'Укажите Ваше имя' => '',
  'Укажите Вашу фамилию' => '',
  'Укажите дату' => '',
  'Укажите дни месяца' => '',
  'Укажите дни недели' => '',
  'Укажите категорию' => '',
  'Укажите контактный телефон' => '',
  'Укажите место/ориентир' => '',
  'Укажите название' => '',
  'Укажите объект' => '',
);
